-- enable treesitter syntax highlighting
vim.cmd("TSBufEnable highlight")

vim.keymap.set("n", "<leader><CR>", function()
	require("nvim-python-repl").send_statement_definition()
end, { desc = "Send semantic unit to REPL" })
vim.keymap.set("v", "<leader><CR>", function()
	require("nvim-python-repl").send_visual_to_repl()
end, { desc = "Send visual selection to REPL" })
vim.keymap.set("n", "<leader>aa", function()
	require("nvim-python-repl").send_buffer_to_repl()
end, { desc = "Send entire buffer to REPL" })
vim.keymap.set("n", "<leader>ae", function()
	require("nvim-python-repl").toggle_execute()
end, { desc = "Automatically execute command in REPL after sent" })
vim.keymap.set("n", "<leader>or", function()
	require("nvim-python-repl").open_repl()
end, { desc = "Opens the REPL in a window split" })
